/home/chris/development/RayLibOdeMech/examples/arm.c File Reference
#include <stdbool.h>
#include "raylibODE.h"
Data Structures
struct grabberData
Macros
#define screenWidth 1920/1.2
#define screenHeight 1080/1.2
Typedefs
typedef struct grabberData grabberData
Functions
void triggerCallback (PhysicsContext *physCtx, dGeomID trigger, dGeomID intruder)
int main (void)
Macro Definition Documentation
screenHeight
#define screenHeight 1080/1.2
Examples
arm.c, car.c, derby.c, fountain.c, gravity.c, marbles.c, piston.c, placer.c, ragdolls.c, raycasting.c, rotor.c, surfaces.c, template.c, and terrain.c.
Definition at line 28 of file arm.c.
Referenced by main().
screenWidth
#define screenWidth 1920/1.2
Examples
arm.c, car.c, derby.c, fountain.c, gravity.c, marbles.c, piston.c, placer.c, ragdolls.c, raycasting.c, rotor.c, surfaces.c, template.c, and terrain.c.
Definition at line 27 of file arm.c.
Referenced by main().
Typedef Documentation
grabberData
typedef struct grabberData grabberData
Function Documentation
main()
int main (void)
Examples
arm.c, car.c, derby.c, fountain.c, gravity.c, marbles.c, piston.c, placer.c, ragdolls.c, raycasting.c, rotor.c, surfaces.c, template.c, and terrain.c.
Definition at line 64 of file arm.c.
References grabberData::attachment, entity::body, GraphicsContext::camera, clistAddNode(), geomInfo::collidable, CreateBox(), CreateCylinder(), CreateGeomInfo(), CreateGraphics(), CreatePhysics(), CreateRandomEntity(), CreateRotor(), CreateSphere(), CreateSphereGeom(), __cnode::data, PhysicsContext::data, DrawBodies(), DrawStatics(), FreeEntity(), FreeGraphics(), FreePhysics(), grabberData::grabber, GraphicsContext::groundTexture, __clist::head, maxPsteps, __cnode::next, NUM_OBJ, PhysicsContext::objList, PLANE_SIZE, PLANE_THICKNESS, grabberData::planeGeom, rndf(), screenHeight, screenWidth, SetEntityHew(), SetupCamera(), SHAPE_ALL, PhysicsContext::space, PhysicsContext::statics, StepPhysics(), triggerCallback(), UpdateCameraControl(), and PhysicsContext::world.
triggerCallback()
void triggerCallback (PhysicsContext * physCtx, dGeomID trigger, dGeomID intruder)
Examples
arm.c, and fountain.c.
Definition at line 42 of file arm.c.
References grabberData::attachment, entity::body, PhysicsContext::data, grabberData::grabber, geomInfo::hew, grabberData::planeGeom, and PhysicsContext::world.
Referenced by main().