/home/chris/development/RayLibOdeMech/examples/car.c File Reference
#include "init.h"
#include "exampleCamera.h"
Macros
#define screenWidth 1920/1.2
#define screenHeight 1080/1.2
Functions
int main (void)
Macro Definition Documentation
screenHeight
#define screenHeight 1080/1.2
Definition at line 29 of file car.c.
screenWidth
#define screenWidth 1920/1.2
Definition at line 28 of file car.c.
Function Documentation
main()
int main (void)
Definition at line 34 of file car.c.
References entity::body, GraphicsContext::camera, CreateGraphics(), CreatePhysics(), CreateRandomEntity(), CreateStaticTrimesh(), CreateVehicle(), __cnode::data, DrawBodies(), DrawStatics(), FreeEntity(), FreeGraphics(), FreePhysics(), FreeVehicle(), GraphicsContext::groundTexture, __clist::head, maxPsteps, __cnode::next, NUM_OBJ, PhysicsContext::objList, rndf(), screenHeight, screenWidth, SetupCamera(), SHAPE_ALL, StepPhysics(), UpdateVehicle(), and UpdateVehicleCamera().