clist.c File Reference
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include "clist.h"
Functions
clist_t * clistCreateList ()
creates a list
cnode_t * clistAddNode (clist_t *list, void *data)
adds a node to a list
cnode_t * clistInsertNode (clist_t *list, cnode_t *node, void *data)
inserts a node at any point in the list
cnode_t * clistFindNode (clist_t *list, void *ptr)
search for a node in the list
void clistDeleteNode (clist_t *list, cnode_t **pnode)
delete a node
void clistDeleteNodeFromData (clist_t *list, void *ptr)
delete a node (containing a pointer)
void clistEmptyList (clist_t *list)
empty a list
void clistFreeList (clist_t **list)
free a list and all its resources
void clistIterateForward (clist_t *list, void(*nodeFunction)(cnode_t *node))
iterate a list
void clistIterateBackward (clist_t *list, void(*nodeFunction)(cnode_t *node))
Iterate backwards through a list.
void clistSort (clist_t *list, int(*cmpFunction)(cnode_t *n1, cnode_t *n2))
sort a list
int clistTotal (clist_t *list)
number of items in list
int clistIsEmpty (clist_t *list)
is list empty?
Function Documentation
clistAddNode()
cnode_t * clistAddNode (clist_t * list, void * data)
adds a node to a list
allocates space for a new node and places the node at the end of the list
Parameters
in list the list to add the node to
in data the data that this node points to
Returns
the newly allocated node
Examples
arm.c, derby.c, fountain.c, piston.c, placer.c, ragdolls.c, rotor.c, and template.c.
Definition at line 47 of file clist.c.
References __cnode::data, __clist::head, __cnode::next, and __clist::tail.
Referenced by CreateBaseEntity(), CreateLift(), CreateRagdoll(), CreateStaticTrimesh(), CreateVehicle(), LoadLevel(), and main().
clistCreateList()
clist_t * clistCreateList ()
creates a list
Allocates space for the list structure clearing the head and tail pointer ready for use.
Returns
provides a pointer to the newly created list
Definition at line 18 of file clist.c.
Referenced by CreatePhysics().
clistDeleteNode()
void clistDeleteNode (clist_t * list, cnode_t ** pnode)
delete a node
this unlinks the node from the list and then frees its memory (the user is responsible for the data the nodes data pointer points to) the pointer to the node (pnode) is then NULLed to aid bug and resource checking
Parameters
in list the list containing the node you wish to delete
in,out pnode a pointer to the node pointer you want to delete, the node pointer is returned NULLed
Definition at line 146 of file clist.c.
References __clist::head, __cnode::next, __cnode::prev, and __clist::tail.
Referenced by clistDeleteNodeFromData(), clistEmptyList(), FreeEntity(), FreeRagdoll(), and FreeVehicle().
clistDeleteNodeFromData()
void clistDeleteNodeFromData (clist_t * list, void * ptr)
delete a node (containing a pointer)
this unlinks the node from the list and then frees its memory (the user is responsible for the data the nodes data pointer points to) the pointer to the node (pnode) is then NULLed to aid bug and resource checking the node is found by searching for a node with a matching data pointer
Parameters
in list the list containing the node you wish to delete
in ptr a pointer to data, for selecting the node
Definition at line 178 of file clist.c.
References clistDeleteNode(), and clistFindNode().
clistEmptyList()
void clistEmptyList (clist_t * list)
empty a list
this will iterate the list freeing all the nodes in it. The list is still valid for use afterwards
Parameters
in list the list you want emptying
Definition at line 198 of file clist.c.
References clistDeleteNode(), and __clist::head.
Referenced by clistFreeList().
clistFindNode()
cnode_t * clistFindNode (clist_t * list, void * ptr)
search for a node in the list
brute force search for a node pointing to specific data generally you should be iterating lists and not dealing with specific nodes individually but this could come in handy
Parameters
in list the list you want to find the node in
in ptr finds the node that points to this data
Returns
checks each node in turn looking for a node that points to ptr returns NULL if it doesn't find a match
Definition at line 119 of file clist.c.
References __cnode::data, __clist::head, and __cnode::next.
Referenced by clistDeleteNodeFromData().
clistFreeList()
void clistFreeList (clist_t ** list)
free a list and all its resources
this empties and frees all resources used by the list. Once freed it cannot be used...
 This does not free what a node is pointing to just the nodes data structure.
Parameters
in,out list The address of the list pointer. It will be freed and then set to NULL to aid bug & resource checking.
Definition at line 219 of file clist.c.
References clistEmptyList().
Referenced by FreePhysics().
clistInsertNode()
cnode_t * clistInsertNode (clist_t * list, cnode_t * node, void * data)
inserts a node at any point in the list
The newly created node takes the position of the inserted node, with the insert node and all subsequent nodes coming after it in the list order
Parameters
in list the list you want to insert the node into
in node the node in the list at the position you want to insert the new node at
in data the data new node points to
Returns
the newly created node is returned
Definition at line 83 of file clist.c.
References __cnode::data, __clist::head, __cnode::next, and __cnode::prev.
clistIsEmpty()
int clistIsEmpty (clist_t * list)
is list empty?
test to see if the list is empty
Parameters
in list
Returns
1 if empty, 0 if at least 1 node
Definition at line 336 of file clist.c.
References __clist::head.
clistIterateBackward()
void clistIterateBackward (clist_t * list, void(* nodeFunction)(cnode_t *node))
Iterate backwards through a list.
identical to clistIterateForwards execept in direction
Parameters
in list the list to iterate
in nodeFunction the callback should return nothing and take only a node pointer as its parameter
Definition at line 267 of file clist.c.
References __cnode::prev, and __clist::tail.
clistIterateForward()
void clistIterateForward (clist_t * list, void(* nodeFunction)(cnode_t *node))
iterate a list
This moves forward through a list calling a callback function for each node in the list. If a callback is not apropriate, because for example you need to access local variables then you should iterate the list in this manner
cnode_t *node=list->head;
while (node!=NULL) {
    // your code here
    node=node->next;
}
Parameters
in list the list to iterate
in nodeFunction the callback should return nothing and take only a node pointer as its parameter
Definition at line 247 of file clist.c.
References __clist::head, and __cnode::next.
clistSort()
void clistSort (clist_t * list, int(* cmpFunction)(cnode_t *n1, cnode_t *n2))
sort a list
does a simple bubble sort on a list depending on node compare callback
Parameters
in list the list to iterate
in cmpFunction the callback which should return 1 if n1 > n2
Definition at line 286 of file clist.c.
References __cnode::data, __clist::head, and __cnode::next.
clistTotal()
int clistTotal (clist_t * list)
number of items in list
This iterrates the list counting all the nodes
Parameters
in list the list you wish to total
Returns
[out] the number of nodes in the list
Definition at line 317 of file clist.c.
References __clist::head, and __cnode::next.