/home/chris/development/RayLibOdeMech/examples/derby.c File Reference
#include <stdlib.h>
#include <math.h>
#include "raylibODE.h"
Macros
#define screenWidth 1920/1.2
#define screenHeight 1080/1.2
#define MAXPATH 32
#define MAXCAR 12
Functions
float GetSteerAngle (Vector2 carPos, Vector2 carForward, Vector2 targetPos)
int main (void)
Macro Definition Documentation
MAXCAR
#define MAXCAR 12
Examples
derby.c.
Referenced by main().
MAXPATH
#define MAXPATH 32
Examples
derby.c.
Referenced by main().
screenHeight
#define screenHeight 1080/1.2
Definition at line 30 of file derby.c.
screenWidth
#define screenWidth 1920/1.2
Definition at line 29 of file derby.c.
Function Documentation
GetSteerAngle()
float GetSteerAngle (Vector2 carPos, Vector2 carForward, Vector2 targetPos)
Examples
derby.c.
Definition at line 32 of file derby.c.
Referenced by main().
main()
int main (void)
Definition at line 56 of file derby.c.
References GraphicsContext::camera, clistAddNode(), CreateGeomInfo(), CreateGraphics(), CreatePhysics(), CreateStaticTrimesh(), CreateVehicle(), DrawBodies(), DrawStatics(), frameCount, FreeGraphics(), FreePhysics(), FreeVehicle(), GetSteerAngle(), GraphicsContext::groundTexture, gSurfaces, MAXCAR, MAXPATH, maxPsteps, OdeToRayMat(), PLANE_THICKNESS, screenHeight, screenWidth, SetupCamera(), PhysicsContext::space, PhysicsContext::statics, StepPhysics(), geomInfo::surface, SURFACE_EARTH, SURFACE_RUBBER, geomInfo::texture, UnflipVehicle(), UpdateCameraControl(), UpdateVehicle(), and geomInfo::visual.