/home/chris/development/RayLibOdeMech/examples/fountain.c File Reference
#include "init.h"
#include "exampleCamera.h"
Macros
#define screenWidth 1920/1.2
#define screenHeight 1080/1.2
Functions
void triggerCallback (PhysicsContext *pctx, dGeomID trigger, dGeomID intruder)
int main (void)
Macro Definition Documentation
screenHeight
#define screenHeight 1080/1.2
Definition at line 28 of file fountain.c.
screenWidth
#define screenWidth 1920/1.2
Definition at line 27 of file fountain.c.
Function Documentation
main()
int main (void)
Definition at line 45 of file fountain.c.
References entity::body, GraphicsContext::camera, clistAddNode(), CreateGeomInfo(), CreateGraphics(), CreatePhysics(), CreateRandomEntity(), __cnode::data, PhysicsContext::data, DrawBodies(), DrawStatics(), FreeEntity(), FreeGraphics(), FreePhysics(), GraphicsContext::groundTexture, __clist::head, maxPsteps, __cnode::next, NUM_OBJ, PhysicsContext::objList, PLANE_SIZE, PLANE_THICKNESS, rndf(), screenHeight, screenWidth, SetEntityHew(), SetupCamera(), SHAPE_ALL, PhysicsContext::space, PhysicsContext::statics, StepPhysics(), triggerCallback(), geomInfo::triggerOnCollide, and UpdateExampleCamera().
triggerCallback()
void triggerCallback (PhysicsContext * pctx, dGeomID trigger, dGeomID intruder)
Definition at line 34 of file fountain.c.
References PhysicsContext::data, and geomInfo::hew.