/home/chris/development/RayLibOdeMech/examples/gravity.c File Reference
#include <math.h>
#include "init.h"
#include "exampleCamera.h"
Macros
#define screenWidth 1920/1.2
#define screenHeight 1080/1.2
#define trailSize 8
Functions
Vector3 GetSpawnOnSphereBorder (Vector3 center, float radius)
entity * CreateOrbiter (PhysicsContext *physCtx, GraphicsContext *graphics)
void updateGravity (PhysicsContext *physCtx, GraphicsContext *graphics)
int main (void)
Variables
int frameCount = 0
Macro Definition Documentation
screenHeight
#define screenHeight 1080/1.2
Definition at line 30 of file gravity.c.
screenWidth
#define screenWidth 1920/1.2
Definition at line 29 of file gravity.c.
trailSize
#define trailSize 8
Definition at line 39 of file gravity.c.
Referenced by CreateOrbiter(), main(), and updateGravity().
Function Documentation
CreateOrbiter()
entity * CreateOrbiter (PhysicsContext * physCtx, GraphicsContext * graphics)
Definition at line 56 of file gravity.c.
References entity::body, CreateSphere(), entity::data, GetSpawnOnSphereBorder(), gSurfaces, rndf(), geomInfo::surface, SURFACE_RUBBER, and trailSize.
Referenced by main(), and updateGravity().
GetSpawnOnSphereBorder()
Vector3 GetSpawnOnSphereBorder (Vector3 center, float radius)
Definition at line 41 of file gravity.c.
References rndf().
Referenced by CreateOrbiter().
main()
int main (void)
Definition at line 93 of file gravity.c.
References GraphicsContext::camera, CreateGraphics(), CreateOrbiter(), CreatePhysics(), __cnode::data, entity::data, DrawBodies(), DrawStatics(), frameCount, FreeGraphics(), FreePhysics(), __clist::head, __cnode::next, NUM_OBJ, PhysicsContext::objList, screenHeight, screenWidth, SetupCamera(), trailSize, UpdateExampleCamera(), updateGravity(), and PhysicsContext::world.
updateGravity()
void updateGravity (PhysicsContext * physCtx, GraphicsContext * graphics)
Definition at line 167 of file gravity.c.
References entity::body, CreateOrbiter(), __cnode::data, entity::data, frameCount, FreeEntity(), __clist::head, __cnode::next, PhysicsContext::objList, StepPhysics(), and trailSize.
Referenced by main().
Variable Documentation
frameCount
int frameCount = 0
Examples
derby.c.
Definition at line 90 of file gravity.c.
Referenced by main(), and updateGravity().