init.c File Reference
Initialization and cleanup functions for graphics and physics.
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "raylibODE.h"
Functions
GraphicsContext * CreateGraphics (int width, int height, const char *title)
Initialize graphics context and window.
PhysicsContext * CreatePhysics ()
Initialize physics world and context.
void FreePhysics (PhysicsContext *ctx)
void FreeGraphics (GraphicsContext *ctx)
Detailed Description
Initialization and cleanup functions for graphics and physics.
This file provides functions to initialize and clean up the graphics and physics subsystems. It handles resource loading, memory allocation, and proper shutdown of all framework components.
Author
Chris Camacho (codifies - http://bedroomcoders.co.uk/)
Date
2026
Initialization Order
Typical initialization sequence:
InitGraphics() - Set up window, models, textures, shaders
InitPhysics() - Create ODE world, space, contact groups
Cleanup Order
Typical cleanup sequence:
CleanupPhysics() - Destroy ODE world, free bodies
CleanupGraphics() - Unload textures, shaders, close window
Definition in file init.c.
Function Documentation
CreateGraphics()
GraphicsContext * CreateGraphics (int width, int height, const char * title)
Initialize graphics context and window.
Sets up the RayLib window, loads all models and textures, compiles shaders, and creates lighting. This must be called before any rendering can occur.
Parameters
width Window width in pixels
height Window height in pixels
title Window title string
Note
Enables VSync and 4x MSAA by default
Hides and locks cursor for FPS-style camera control
Loads default textures from data/ directory
See also
GraphicsContext
FreeGraphics
Examples
arm.c, car.c, derby.c, fountain.c, piston.c, placer.c, ragdolls.c, rotor.c, template.c, and terrain.c.
Definition at line 77 of file init.c.
References GraphicsContext::ball, GraphicsContext::box, GraphicsContext::boxTextures, CreateLight(), GraphicsContext::cylinder, GraphicsContext::cylinderTextures, GraphicsContext::groundTexture, LIGHT_POINT, GraphicsContext::lights, GraphicsContext::shader, and GraphicsContext::sphereTextures.
CreatePhysics()
PhysicsContext * CreatePhysics ()
Initialize physics world and context.
Creates and configures the ODE physics world, collision space, and contact group. Also seeds the random number generator.
Returns
Pointer to newly created PhysicsContext
Note
Checks for single-precision ODE build (required)
Sets gravity to -9.8 m/s^2 (Earth gravity)
Enables auto-disable for resting bodies
Warning
Exits with error message if precision mismatch detected
See also
CleanupPhysics
PhysicsContext
Examples
arm.c, car.c, derby.c, fountain.c, piston.c, placer.c, ragdolls.c, rotor.c, template.c, and terrain.c.
Definition at line 158 of file init.c.
References clistCreateList(), PhysicsContext::contactgroup, PhysicsContext::objList, PhysicsContext::space, PhysicsContext::statics, and PhysicsContext::world.
FreeGraphics()
void FreeGraphics (GraphicsContext * ctx)
Examples
arm.c, car.c, derby.c, fountain.c, piston.c, placer.c, ragdolls.c, rotor.c, template.c, and terrain.c.
Definition at line 246 of file init.c.
References GraphicsContext::ball, GraphicsContext::box, GraphicsContext::boxTextures, GraphicsContext::cylinder, GraphicsContext::cylinderTextures, GraphicsContext::groundTexture, GraphicsContext::shader, and GraphicsContext::sphereTextures.
FreePhysics()
void FreePhysics (PhysicsContext * ctx)
Examples
arm.c, car.c, derby.c, fountain.c, piston.c, placer.c, ragdolls.c, rotor.c, template.c, and terrain.c.
Definition at line 195 of file init.c.
References entity::body, clistFreeList(), PhysicsContext::contactgroup, __cnode::data, FreeBodyAndGeoms(), __clist::head, geomInfo::indices, __cnode::next, PhysicsContext::objList, PhysicsContext::space, PhysicsContext::statics, geomInfo::triData, and PhysicsContext::world.