/home/chris/development/RayLibOdeMech/examples/marbles.c File Reference
#include <stdlib.h>
#include <math.h>
#include "raylibODE.h"
Data Structures
struct LevelElement
Macros
#define screenWidth 1920/1.2
#define screenHeight 1080/1.2
#define MAX_PISTON 6
Typedefs
typedef struct LevelElement LevelElement
Enumerations
enum MeshType { SLOPE
, STRAIGHT
, CORNER
 }
Functions
void LoadLevel (PhysicsContext *physCtx, GraphicsContext *graphics)
MultiPiston ** CreateLift (PhysicsContext *physCtx, GraphicsContext *graphics, Vector3 position, float yaw, float strength)
int main (void)
Variables
const SurfaceType levelSurface = SURFACE_WOOD
LevelElement levelData []
Macro Definition Documentation
MAX_PISTON
#define MAX_PISTON 6
Examples
marbles.c.
Definition at line 45 of file marbles.c.
Referenced by CreateLift(), and main().
screenHeight
#define screenHeight 1080/1.2
Definition at line 42 of file marbles.c.
screenWidth
#define screenWidth 1920/1.2
Definition at line 41 of file marbles.c.
Typedef Documentation
LevelElement
typedef struct LevelElement LevelElement
Enumeration Type Documentation
MeshType
enum MeshType
Enumerator
SLOPE
STRAIGHT
CORNER
Examples
marbles.c.
Definition at line 47 of file marbles.c.
Function Documentation
CreateLift()
MultiPiston ** CreateLift (PhysicsContext * physCtx, GraphicsContext * graphics, Vector3 position, float yaw, float strength)
Examples
marbles.c.
Definition at line 378 of file marbles.c.
References clistAddNode(), CreateBoxGeom(), CreateMultiPiston(), MAX_PISTON, PinEntityToWorld(), and PhysicsContext::statics.
Referenced by main().
LoadLevel()
void LoadLevel (PhysicsContext * physCtx, GraphicsContext * graphics)
Examples
marbles.c.
Definition at line 249 of file marbles.c.
References LevelElement::angle, clistAddNode(), CORNER, CreateCylinderGeom(), LevelElement::gridX, LevelElement::gridY, LevelElement::gridZ, gSurfaces, levelData, levelSurface, SLOPE, PhysicsContext::statics, STRAIGHT, geomInfo::surface, and LevelElement::type.
Referenced by main().
main()
int main (void)
Definition at line 132 of file marbles.c.
References entity::body, GraphicsContext::camera, CreateGraphics(), CreateLift(), CreatePhysics(), CreateSphere(), __cnode::data, DrawBodies(), DrawStatics(), frameCount, FreeEntity(), FreeGraphics(), FreeMultiPiston(), FreePhysics(), gSurfaces, __clist::head, LoadLevel(), MAX_PISTON, __cnode::next, PhysicsContext::objList, screenHeight, screenWidth, SetCameraYaw(), SetMultiPistonVelocity(), SetupCamera(), StepPhysics(), geomInfo::surface, SURFACE_METAL, and UpdateCameraControl().
Variable Documentation
levelData
LevelElement levelData[]
Examples
marbles.c.
Definition at line 59 of file marbles.c.
Referenced by LoadLevel().
levelSurface
const SurfaceType levelSurface = SURFACE_WOOD
Examples
marbles.c.
Definition at line 44 of file marbles.c.
Referenced by LoadLevel().