/home/chris/development/RayLibOdeMech/examples/pidJoint.c File Reference
#include "init.h"
#include "exampleCamera.h"
Macros
#define screenWidth 1920/1.2
#define screenHeight 1080/1.2
Functions
int main (void)
Macro Definition Documentation
screenHeight
#define screenHeight 1080/1.2
Definition at line 30 of file pidJoint.c.
screenWidth
#define screenWidth 1920/1.2
Definition at line 29 of file pidJoint.c.
Function Documentation
main()
int main (void)
Definition at line 34 of file pidJoint.c.
References entity::body, GraphicsContext::camera, clistAddNode(), MultiPiston::count, CreateCylinder(), CreateGeomInfo(), CreateGraphics(), CreateMultiPiston(), CreatePhysics(), CreateRandomEntity(), CreateRotor(), CreateRotorPID(), CreateSphere(), __cnode::data, DrawBodies(), DrawStatics(), FreeEntity(), FreeGraphics(), FreeMultiPiston(), FreePhysics(), GraphicsContext::groundTexture, __clist::head, __cnode::next, PhysicsContext::objList, PinEntities(), PLANE_SIZE, PLANE_THICKNESS, rndf(), screenHeight, screenWidth, MultiPiston::sections, SetMultiPistonVelocity(), SetupCamera(), SHAPE_ALL, PhysicsContext::space, PhysicsContext::statics, StepPhysics(), RotorPID::targetAngle, UpdateExampleCamera(), and UpdateRotorPID().