/home/chris/development/RayLibOdeMech/examples/piston.c File Reference
#include "init.h"
#include "exampleCamera.h"
Macros
#define screenWidth 1920/1.2
#define screenHeight 1080/1.2
Functions
int main (void)
Macro Definition Documentation
screenHeight
#define screenHeight 1080/1.2
Definition at line 28 of file piston.c.
screenWidth
#define screenWidth 1920/1.2
Definition at line 27 of file piston.c.
Function Documentation
main()
int main (void)
Definition at line 32 of file piston.c.
References entity::body, GraphicsContext::camera, clistAddNode(), CreateBox(), CreateGeomInfo(), CreateGraphics(), CreateMultiPiston(), CreatePhysics(), CreatePiston(), CreateRandomEntity(), __cnode::data, DrawBodies(), DrawStatics(), FreeEntity(), FreeGraphics(), FreeMultiPiston(), FreePhysics(), GraphicsContext::groundTexture, __clist::head, __cnode::next, NUM_OBJ, PhysicsContext::objList, PinEntityToWorld(), PISTON_GROUP, PLANE_SIZE, PLANE_THICKNESS, rndf(), screenHeight, screenWidth, MultiPiston::sections, SetBodyOrientation(), SetMultiPistonVelocity(), SetPistonLimits(), SetupCamera(), SHAPE_ALL, PhysicsContext::space, PhysicsContext::statics, StepPhysics(), UpdateExampleCamera(), and WORLD_GROUP.