/home/chris/development/RayLibOdeMech/examples/placer.c File Reference
#include "raylibODE.h"
Macros
#define screenWidth 1920/1.2
#define screenHeight 1080/1.2
Functions
int main (void)
Macro Definition Documentation
screenHeight
#define screenHeight 1080/1.2
Definition at line 28 of file placer.c.
screenWidth
#define screenWidth 1920/1.2
Definition at line 27 of file placer.c.
Function Documentation
main()
int main (void)
Definition at line 32 of file placer.c.
References entity::body, GraphicsContext::camera, clistAddNode(), CreateBox(), CreateCapsule(), CreateCylinder(), CreateDumbbell(), CreateGeomInfo(), CreateGraphics(), CreatePhysics(), CreateRandomEntity(), CreateSphere(), __cnode::data, DrawBodies(), DrawStatics(), FreeEntity(), FreeGraphics(), FreePhysics(), GetCameraYaw(), GraphicsContext::groundTexture, __clist::head, __cnode::next, NUM_OBJ, PhysicsContext::objList, PickEntity(), PLANE_SIZE, PLANE_THICKNESS, rndf(), screenHeight, screenWidth, SetupCamera(), SHAPE_ALL, PhysicsContext::space, PhysicsContext::statics, StepPhysics(), and UpdateCameraControl().