ragdoll.c File Reference
Ragdoll physics simulation implementation.
#include "raylibODE.h"
#include "ragdoll.h"
Functions
Vector3 GetRagdollSpawnPosition (void)
Get a random spawn position for ragdolls.
RagDoll * CreateRagdoll (struct PhysicsContext *pctx, struct GraphicsContext *ctx, Vector3 position)
Create a ragdoll physics body.
void UpdateRagdollMotors (RagDoll *ragdoll, float *motorForces)
Update ragdoll joint motors.
void DrawRagdoll (RagDoll *ragdoll, struct GraphicsContext *ctx)
Render a ragdoll to the screen.
void FreeRagdoll (PhysicsContext *ctx, RagDoll *ragdoll)
Free a ragdoll and all its resources.
Detailed Description
Ragdoll physics simulation implementation.
This file provides a complete ragdoll (humanoid) physics simulation using ODE's joint system. The ragdoll consists of multiple body parts connected by hinge and universal joints, allowing for realistic human-like movement and posing.
Author
Chris Camacho (codifies - http://bedroomcoders.co.uk/)
Date
2026
Ragdoll Structure
Body parts (10 total):
Head (sphere)
Torso (box)
Left/Right Upper Arm (capsule)
Left/Right Lower Arm (capsule)
Left/Right Upper Leg (capsule)
Left/Right Lower Leg (capsule)
Joints (9 total):
Neck (hinge)
Left/Right Shoulder (universal)
Left/Right Elbow (hinge)
Left/Right Hip (universal)
Left/Right Knee (hinge)
Motor Control
The ragdoll supports motor control on all joints, making it suitable for neural network or reinforcement learning control. Use UpdateRagdollMotors() to apply forces to joints.
Definition in file ragdoll.c.
Function Documentation
CreateRagdoll()
RagDoll * CreateRagdoll (struct PhysicsContext * pctx, struct GraphicsContext * ctx, Vector3 position)
Create a ragdoll physics body.
Creates a complete humanoid ragdoll with articulated joints. The ragdoll is fully physics-simulated and can be used for character physics, death animations, or as a basis for reinforcement learning control.
Parameters
pctx Pointer to physics context
ctx Pointer to graphics context
position Initial position for the ragdoll
Returns
Pointer to newly created RagDoll structure
Note
Bodies: 10 (head, torso, 2 upper arms, 2 lower arms, 2 upper legs, 2 lower legs)
Joints: 9 (neck, shoulders, elbows, hips, knees)
All bodies are registered with framework for rendering
See also
RagDoll
UpdateRagdollMotors
DrawRagdoll
FreeRagdoll
Examples
ragdolls.c.
Definition at line 117 of file ragdoll.c.
References RagDoll::bodies, entity::body, RagDoll::bodyCount, GraphicsContext::boxTextures, clistAddNode(), CreateGeomInfo(), GraphicsContext::cylinderTextures, RagDoll::geoms, RagDoll::jointCount, RagDoll::joints, RagDoll::motorCount, RagDoll::motors, entity::node, PhysicsContext::objList, RAGDOLL_BODY_COUNT, RAGDOLL_HEAD, RAGDOLL_LEFT_LOWER_ARM, RAGDOLL_LEFT_LOWER_LEG, RAGDOLL_LEFT_UPPER_ARM, RAGDOLL_LEFT_UPPER_LEG, RAGDOLL_RIGHT_LOWER_ARM, RAGDOLL_RIGHT_LOWER_LEG, RAGDOLL_RIGHT_UPPER_ARM, RAGDOLL_RIGHT_UPPER_LEG, RAGDOLL_TORSO, PhysicsContext::space, GraphicsContext::sphereTextures, and PhysicsContext::world.
DrawRagdoll()
void DrawRagdoll (RagDoll * ragdoll, struct GraphicsContext * ctx)
Render a ragdoll to the screen.
Renders all body parts of the ragdoll using the framework's existing rendering system.
Parameters
ragdoll Pointer to the ragdoll structure
ctx Pointer to the graphics context
Note
Uses the same drawGeom system as other physics bodies
See also
CreateRagdoll
Definition at line 454 of file ragdoll.c.
References RagDoll::bodyCount, DrawGeom(), and RagDoll::geoms.
FreeRagdoll()
void FreeRagdoll (PhysicsContext * ctx, RagDoll * ragdoll)
Free a ragdoll and all its resources.
Properly destroys all ODE bodies, geoms, joints, and motors associated with the ragdoll, and frees the wrapper structure.
Parameters
ctx Pointer to physics context
ragdoll Pointer to the ragdoll structure to free
Note
Removes ragdoll from framework's object list
Frees all allocated memory for bodies, geoms, joints
See also
CreateRagdoll
Examples
ragdolls.c.
Definition at line 482 of file ragdoll.c.
References RagDoll::bodies, RagDoll::bodyCount, clistDeleteNode(), FreeBodyAndGeoms(), RagDoll::geoms, RagDoll::jointCount, RagDoll::joints, RagDoll::motorCount, RagDoll::motors, entity::node, and PhysicsContext::objList.
GetRagdollSpawnPosition()
Vector3 GetRagdollSpawnPosition (void)
Get a random spawn position for ragdolls.
Generates a random position within the configured spawn volume for ragdoll objects. This helps spread out multiple ragdolls when they are created.
Returns
Random Vector3 position within spawn bounds
Note
Spawn bounds are defined by RAGDOLL_SPAWN_* constants
See also
RAGDOLL_SPAWN_CENTER_X
RAGDOLL_SPAWN_CENTER_Z
RAGDOLL_SPAWN_HALF_EXTENT
RAGDOLL_SPAWN_MIN_Y
RAGDOLL_SPAWN_MAX_Y
Examples
ragdolls.c.
Definition at line 81 of file ragdoll.c.
References RAGDOLL_SPAWN_CENTER_X, RAGDOLL_SPAWN_CENTER_Z, RAGDOLL_SPAWN_HALF_EXTENT, RAGDOLL_SPAWN_MAX_Y, RAGDOLL_SPAWN_MIN_Y, and rndf().
UpdateRagdollMotors()
void UpdateRagdollMotors (RagDoll * ragdoll, float * motorForces)
Update ragdoll joint motors.
Applies motor forces to the ragdoll's joints for control. This is useful for neural network or reinforcement learning control of the ragdoll.
Parameters
ragdoll Pointer to the ragdoll structure
motorForces Array of motor force values (one per joint)
Note
Array should have ragdoll->jointCount elements for hinge joints
For universal joints, uses ragdoll->jointCount * 2 elements
Force of 0 disables the motor for that joint
See also
CreateRagdoll
Definition at line 416 of file ragdoll.c.
References RagDoll::jointCount, and RagDoll::joints.