ragdoll.h File Reference
#include "raylib.h"
#include <ode/ode.h>
Data Structures
struct RagDoll
Macros
#define RAGDOLL_SPAWN_CENTER_X 0.0f
#define RAGDOLL_SPAWN_CENTER_Z 0.0f
#define RAGDOLL_SPAWN_HALF_EXTENT 3.0f
#define RAGDOLL_SPAWN_MIN_Y 1.6f
#define RAGDOLL_SPAWN_MAX_Y 2.6f
Typedefs
typedef struct RagDoll RagDoll
Enumerations
enum RagdollBodyPart {
RAGDOLL_HEAD = 0
, RAGDOLL_TORSO
, RAGDOLL_LEFT_UPPER_ARM
, RAGDOLL_LEFT_LOWER_ARM
,
RAGDOLL_RIGHT_UPPER_ARM
, RAGDOLL_RIGHT_LOWER_ARM
, RAGDOLL_LEFT_UPPER_LEG
, RAGDOLL_LEFT_LOWER_LEG
,
RAGDOLL_RIGHT_UPPER_LEG
, RAGDOLL_RIGHT_LOWER_LEG
, RAGDOLL_BODY_COUNT
 }
Functions
RagDoll * CreateRagdoll (struct PhysicsContext *pctx, struct GraphicsContext *ctx, Vector3 position)
Create a ragdoll physics body.
void UpdateRagdollMotors (RagDoll *ragdoll, float *motorForces)
Update ragdoll joint motors.
void DrawRagdoll (RagDoll *ragdoll, struct GraphicsContext *ctx)
Render a ragdoll to the screen.
void FreeRagdoll (PhysicsContext *ctx, RagDoll *ragdoll)
Free a ragdoll and all its resources.
Vector3 GetRagdollSpawnPosition (void)
Get a random spawn position for ragdolls.
Macro Definition Documentation
RAGDOLL_SPAWN_CENTER_X
#define RAGDOLL_SPAWN_CENTER_X 0.0f
Definition at line 72 of file ragdoll.h.
Referenced by GetRagdollSpawnPosition().
RAGDOLL_SPAWN_CENTER_Z
#define RAGDOLL_SPAWN_CENTER_Z 0.0f
Definition at line 73 of file ragdoll.h.
Referenced by GetRagdollSpawnPosition().
RAGDOLL_SPAWN_HALF_EXTENT
#define RAGDOLL_SPAWN_HALF_EXTENT 3.0f
Definition at line 74 of file ragdoll.h.
Referenced by GetRagdollSpawnPosition().
RAGDOLL_SPAWN_MAX_Y
#define RAGDOLL_SPAWN_MAX_Y 2.6f
Definition at line 76 of file ragdoll.h.
Referenced by GetRagdollSpawnPosition().
RAGDOLL_SPAWN_MIN_Y
#define RAGDOLL_SPAWN_MIN_Y 1.6f
Definition at line 75 of file ragdoll.h.
Referenced by GetRagdollSpawnPosition().
Typedef Documentation
RagDoll
typedef struct RagDoll RagDoll
Enumeration Type Documentation
RagdollBodyPart
enum RagdollBodyPart
Enumerator
RAGDOLL_HEAD
RAGDOLL_TORSO
RAGDOLL_LEFT_UPPER_ARM
RAGDOLL_LEFT_LOWER_ARM
RAGDOLL_RIGHT_UPPER_ARM
RAGDOLL_RIGHT_LOWER_ARM
RAGDOLL_LEFT_UPPER_LEG
RAGDOLL_LEFT_LOWER_LEG
RAGDOLL_RIGHT_UPPER_LEG
RAGDOLL_RIGHT_LOWER_LEG
RAGDOLL_BODY_COUNT
Definition at line 45 of file ragdoll.h.
Function Documentation
CreateRagdoll()
RagDoll * CreateRagdoll (struct PhysicsContext * pctx, struct GraphicsContext * ctx, Vector3 position)
Create a ragdoll physics body.
Creates a complete humanoid ragdoll with articulated joints. The ragdoll is fully physics-simulated and can be used for character physics, death animations, or as a basis for reinforcement learning control.
Parameters
pctx Pointer to physics context
ctx Pointer to graphics context
position Initial position for the ragdoll
Returns
Pointer to newly created RagDoll structure
Note
Bodies: 10 (head, torso, 2 upper arms, 2 lower arms, 2 upper legs, 2 lower legs)
Joints: 9 (neck, shoulders, elbows, hips, knees)
All bodies are registered with framework for rendering
See also
RagDoll
UpdateRagdollMotors
DrawRagdoll
FreeRagdoll
Definition at line 117 of file ragdoll.c.
References RagDoll::bodies, entity::body, RagDoll::bodyCount, GraphicsContext::boxTextures, clistAddNode(), CreateGeomInfo(), GraphicsContext::cylinderTextures, RagDoll::geoms, RagDoll::jointCount, RagDoll::joints, RagDoll::motorCount, RagDoll::motors, entity::node, PhysicsContext::objList, RAGDOLL_BODY_COUNT, RAGDOLL_HEAD, RAGDOLL_LEFT_LOWER_ARM, RAGDOLL_LEFT_LOWER_LEG, RAGDOLL_LEFT_UPPER_ARM, RAGDOLL_LEFT_UPPER_LEG, RAGDOLL_RIGHT_LOWER_ARM, RAGDOLL_RIGHT_LOWER_LEG, RAGDOLL_RIGHT_UPPER_ARM, RAGDOLL_RIGHT_UPPER_LEG, RAGDOLL_TORSO, PhysicsContext::space, GraphicsContext::sphereTextures, and PhysicsContext::world.
DrawRagdoll()
void DrawRagdoll (RagDoll * ragdoll, struct GraphicsContext * ctx)
Render a ragdoll to the screen.
Renders all body parts of the ragdoll using the framework's existing rendering system.
Parameters
ragdoll Pointer to the ragdoll structure
ctx Pointer to the graphics context
Note
Uses the same drawGeom system as other physics bodies
See also
CreateRagdoll
Definition at line 454 of file ragdoll.c.
References RagDoll::bodyCount, DrawGeom(), and RagDoll::geoms.
FreeRagdoll()
void FreeRagdoll (PhysicsContext * ctx, RagDoll * ragdoll)
Free a ragdoll and all its resources.
Properly destroys all ODE bodies, geoms, joints, and motors associated with the ragdoll, and frees the wrapper structure.
Parameters
ctx Pointer to physics context
ragdoll Pointer to the ragdoll structure to free
Note
Removes ragdoll from framework's object list
Frees all allocated memory for bodies, geoms, joints
See also
CreateRagdoll
Definition at line 482 of file ragdoll.c.
References RagDoll::bodies, RagDoll::bodyCount, clistDeleteNode(), FreeBodyAndGeoms(), RagDoll::geoms, RagDoll::jointCount, RagDoll::joints, RagDoll::motorCount, RagDoll::motors, entity::node, and PhysicsContext::objList.
GetRagdollSpawnPosition()
Vector3 GetRagdollSpawnPosition (void)
Get a random spawn position for ragdolls.
Generates a random position within the configured spawn volume for ragdoll objects. This helps spread out multiple ragdolls when they are created.
Returns
Random Vector3 position within spawn bounds
Note
Spawn bounds are defined by RAGDOLL_SPAWN_* constants
See also
RAGDOLL_SPAWN_CENTER_X
RAGDOLL_SPAWN_CENTER_Z
RAGDOLL_SPAWN_HALF_EXTENT
RAGDOLL_SPAWN_MIN_Y
RAGDOLL_SPAWN_MAX_Y
Definition at line 81 of file ragdoll.c.
References RAGDOLL_SPAWN_CENTER_X, RAGDOLL_SPAWN_CENTER_Z, RAGDOLL_SPAWN_HALF_EXTENT, RAGDOLL_SPAWN_MAX_Y, RAGDOLL_SPAWN_MIN_Y, and rndf().
UpdateRagdollMotors()
void UpdateRagdollMotors (RagDoll * ragdoll, float * motorForces)
Update ragdoll joint motors.
Applies motor forces to the ragdoll's joints for control. This is useful for neural network or reinforcement learning control of the ragdoll.
Parameters
ragdoll Pointer to the ragdoll structure
motorForces Array of motor force values (one per joint)
Note
Array should have ragdoll->jointCount elements for hinge joints
For universal joints, uses ragdoll->jointCount * 2 elements
Force of 0 disables the motor for that joint
See also
CreateRagdoll
Definition at line 416 of file ragdoll.c.
References RagDoll::jointCount, and RagDoll::joints.