/home/chris/development/RayLibOdeMech/examples/ragdolls.c File Reference
#include "init.h"
#include "exampleCamera.h"
#include "ragdoll.h"
Macros
#define screenWidth 1920/1.2
#define screenHeight 1080/1.2
#define NRAGDOLLS 16
Functions
int main (void)
Macro Definition Documentation
NRAGDOLLS
#define NRAGDOLLS 16
Examples
ragdolls.c.
Definition at line 31 of file ragdolls.c.
Referenced by main().
screenHeight
#define screenHeight 1080/1.2
Definition at line 29 of file ragdolls.c.
screenWidth
#define screenWidth 1920/1.2
Definition at line 28 of file ragdolls.c.
Function Documentation
main()
int main (void)
Definition at line 34 of file ragdolls.c.
References RagDoll::bodyCount, GraphicsContext::camera, clistAddNode(), CreateGeomInfo(), CreateGraphics(), CreatePhysics(), CreateRagdoll(), DrawBodies(), DrawStatics(), FreeGraphics(), FreePhysics(), FreeRagdoll(), GetRagdollSpawnPosition(), GraphicsContext::groundTexture, maxPsteps, NRAGDOLLS, PLANE_SIZE, PLANE_THICKNESS, RAGDOLL_HEAD, RAGDOLL_TORSO, rndf(), screenHeight, screenWidth, SetupCamera(), PhysicsContext::space, PhysicsContext::statics, StepPhysics(), and UpdateExampleCamera().