/home/chris/development/RayLibOdeMech/examples/raycasting.c File Reference
#include "raylibODE.h"
Macros
#define screenWidth 1920/1.2
#define screenHeight 1080/1.2
Functions
int main (void)
Macro Definition Documentation
screenHeight
#define screenHeight 1080/1.2
Definition at line 28 of file raycasting.c.
screenWidth
#define screenWidth 1920/1.2
Definition at line 27 of file raycasting.c.
Function Documentation
main()
int main (void)
Definition at line 32 of file raycasting.c.
References entity::body, GraphicsContext::camera, CastRay(), clistAddNode(), RayCast::count, CreateBox(), CreateGeomInfo(), CreateGraphics(), CreatePhysics(), CreateRayCast(), __cnode::data, RayCast::direction, DrawBodies(), DrawStatics(), frameCount, FreeEntity(), FreeGraphics(), FreePhysics(), RayHit::geom, gSurfaces, __clist::head, geomInfo::hew, RayCast::hits, RayCast::length, maxPsteps, __cnode::next, PhysicsContext::objList, PLANE_SIZE, PLANE_THICKNESS, RayCast::position, screenHeight, screenWidth, SetEntitySurfaces(), SetGeomOrientationEuler(), SetupCamera(), PhysicsContext::space, PhysicsContext::statics, StepPhysics(), geomInfo::surface, SURFACE_ICE, and UpdateCameraControl().