raylibODE.c File Reference
Core physics and rendering integration for RayLib-ODE framework.
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "raylibODE.h"
#include "collision.h"
Functions
float rndf (float min, float max)
Generate a random float in the specified range.
int StepPhysics (PhysicsContext *physCtx)
Step the physics simulation forward.
entity * CreateBaseEntity (PhysicsContext *ctx)
Create a base entity with physics body.
dGeomID CreateSphereGeom (PhysicsContext *ctx, GraphicsContext *gfxCtx, float radius, Vector3 pos)
dGeomID CreateCylinderGeom (PhysicsContext *ctx, GraphicsContext *gfxCtx, float radius, float length, Vector3 pos)
dGeomID CreateBoxGeom (PhysicsContext *ctx, GraphicsContext *gfxCtx, Vector3 size, Vector3 pos)
entity * CreateBox (PhysicsContext *ctx, GraphicsContext *gfxCtx, Vector3 size, Vector3 pos, Vector3 rot, float mass)
Add a box-shaped physics body to the world.
entity * CreateSphere (PhysicsContext *ctx, GraphicsContext *gfxCtx, float radius, Vector3 pos, Vector3 rot, float mass)
Add a sphere-shaped physics body to the world.
entity * CreateCylinder (PhysicsContext *ctx, GraphicsContext *gfxCtx, float radius, float length, Vector3 pos, Vector3 rot, float mass)
Add a cylinder-shaped physics body to the world.
entity * CreateCapsule (PhysicsContext *ctx, GraphicsContext *gfxCtx, float radius, float length, Vector3 pos, Vector3 rot, float mass)
Add a capsule-shaped physics body to the world.
entity * CreateDumbbell (PhysicsContext *ctx, GraphicsContext *gfxCtx, float shaftRad, float shaftLen, float endRad, Vector3 pos, Vector3 rot, float mass)
Add a dumbbell-shaped composite physics body.
entity * CreateRandomEntity (PhysicsContext *ctx, GraphicsContext *gfxCtx, Vector3 pos, unsigned char mask)
Add a random physics object at the specified position.
cnode_t * CreateStaticTrimesh (PhysicsContext *physCtx, GraphicsContext *gfxCtx, Model model, Texture *tex, float uvScale)
Create a static trimesh collision geometry from a model.
geomInfo * CreateGeomInfo (bool collidable, Texture *texture, float uvScaleU, float uvScaleV)
Helper to allocate geomInfo with collision flag, optional texture, and UV scale this is useful when greating your own custom bodies for special purposes If this is attached to a geom on a body that is in the global entity list then this allocation will be automagically cleaned up.
entity * PickEntity (PhysicsContext *physCtx, GraphicsContext *gfxCtx, Vector3 *hitPoint)
this will return the first entity that the camera is directly pointed at while useful in the examples and likely for other things, it also serves as an example of how you can do this yourself for other things
RayCast * CreateRayCast (int maxHits, Vector3 pos, Vector3 direction, dReal length)
find the entities that collide with a ray
void CastRay (PhysicsContext *physCtx, RayCast *rc)
void FreeBodyAndGeoms (dBodyID bdy)
given a body it will remove it and its geoms from ODE's world
void RayToOdeMat (Matrix *m, dReal *R)
set an ODE matrix to the same as a Raylib Matrix
void OdeToRayMat (const dReal *R, Matrix *m)
sets a raylib matrix from an ODE rotation matrix
void DrawGeom (dGeomID geom, struct GraphicsContext *ctx)
dJointID CreateRotor (PhysicsContext *physCtx, entity *from, entity *to, Vector3 axis)
crates a rotor joint the joint is created with the anchor at the from enties location
void SetEntityHew (entity *ent, Color c)
changes the hew (tint) of all anentities geoms
void SetEntitySurfaces (entity *ent, SurfaceMaterial *mat)
changes the surface material of all an entities geoms
void DrawBodies (struct GraphicsContext *ctx, PhysicsContext *pctx)
Draws all the dynamic bodies the framework is tracking.
void DrawStatics (struct GraphicsContext *ctx, PhysicsContext *pctx)
draws the static geometries
void FreeEntity (PhysicsContext *physCtx, entity *ent)
frees an entity
dJointID CreatePiston (PhysicsContext *physCtx, entity *entA, entity *entB, float strength)
creates a piston using two entities as its base on extending sections
void SetPistonLimits (dJointID joint, float min, float max)
sets the limits of travel for a piston
void FreeMultiPiston (MultiPiston *mp)
frees all the internal resources of a multipiston
MultiPiston * CreateMultiPiston (PhysicsContext *physCtx, GraphicsContext *graphics, Vector3 pos, Vector3 direction, int count, float sectionLen, float baseWidth, float strength)
add a multi section piston
void SetMultiPistonVelocity (MultiPiston *mp, float velocity)
set a MultiPiston's velocity
void SetBodyOrientation (dBodyID body, Vector3 direction)
sets to bodies orientation to align with a vector
dJointID PinEntityToWorld (PhysicsContext *physCtx, entity *ent)
pins an entity to the world
dJointID PinEntities (PhysicsContext *physCtx, entity *entA, entity *entB)
pin two entities together
void SetBodyOrientationEuler (dBodyID bdy, float p, float y, float r)
sets a bodies orientation
void SetGeomOrientationEuler (dGeomID g, float p, float y, float r)
sets a geoms orientation
RotorPID CreateRotorPID (float p, float i, float d, float lo, float hi)
create a rotor PID helper
void UpdateRotorPID (RotorPID *pid, dJointID joint)
update rotor PID
Variables
const float physSlice = 1.0 / 240.0
Physics simulation time slice.
Detailed Description
Core physics and rendering integration for RayLib-ODE framework.
This file contains the main framework functions for creating physics bodies, handling collisions, and rendering geometric primitives. It serves as the bridge between RayLib's rendering system and ODE's physics engine.
Author
Chris Camacho (codifies - http://bedroomcoders.co.uk/)
Date
2021-2026
Definition in file raylibODE.c.
Function Documentation
CastRay()
void CastRay (PhysicsContext * physCtx, RayCast * rc)
cast a ray into the world building an array of results
Parameters
physCtx physics context
rc raycast holding ray properties and results
Note
the array of hits produced is not in depth order, and built as ode iterates the world body list which is in no particular order
Examples
raycasting.c.
Definition at line 876 of file raylibODE.c.
References RayCast::count, RayCast::direction, RayCast::length, RayCast::position, and PhysicsContext::space.
Referenced by main().
CreateBaseEntity()
entity * CreateBaseEntity (PhysicsContext * ctx)
Create a base entity with physics body.
Internal helper function that creates a new entity with an ODE body and adds it to the physics world's object list. This reduces code duplication across all shape creation functions.
Parameters
ctx Pointer to the physics context
Returns
Pointer to newly created entity
Note
Internal function - but might be useful for manual creation it creates an "empty" body without geoms
Definition at line 303 of file raylibODE.c.
References entity::body, clistAddNode(), entity::node, PhysicsContext::objList, and PhysicsContext::world.
Referenced by CreateBox(), CreateCapsule(), CreateCylinder(), CreateDumbbell(), and CreateSphere().
CreateBox()
entity * CreateBox (PhysicsContext * ctx, GraphicsContext * gfxCtx, Vector3 size, Vector3 pos, Vector3 rot, float mass)
Add a box-shaped physics body to the world.
Creates a new dynamic box in the physics simulation with the specified dimensions, position, rotation, and mass. The box is automatically added to the rendering list and collision detection system.
Parameters
ctx Pointer to the physics context
gfxCtx Pointer to the graphics context for texture assignment
size Dimensions of the box (width, height, depth)
pos Initial position of the box center
rot Initial rotation (Euler angles: pitch, yaw, roll)
mass Mass of the box (0 for static object)
Returns
Pointer to the newly created entity
Note
Box is assigned a random texture from the available box textures
See also
entity
PhysicsContext
GraphicsContext
Examples
arm.c, piston.c, placer.c, raycasting.c, rotor.c, and surfaces.c.
Definition at line 417 of file raylibODE.c.
References entity::body, GraphicsContext::boxTextures, CreateBaseEntity(), CreateGeomInfo(), rndf(), and PhysicsContext::space.
Referenced by CreateMultiPiston(), CreateRandomEntity(), and main().
CreateBoxGeom()
dGeomID CreateBoxGeom (PhysicsContext * ctx, GraphicsContext * gfxCtx, Vector3 size, Vector3 pos)
Create a box geom
This creates just the geometry, useful for building composite shapes
Parameters
ctx the physics context
gfxCtx the graphics context
size the size of the sphere
pos where you want the geom positioned
Note
if you want to use this as a static collider in the world you will need to add it to the world and the physics context statics list
Examples
marbles.c.
Definition at line 383 of file raylibODE.c.
References GraphicsContext::boxTextures, CreateGeomInfo(), rndf(), and PhysicsContext::space.
Referenced by CreateLift().
CreateCapsule()
entity * CreateCapsule (PhysicsContext * ctx, GraphicsContext * gfxCtx, float radius, float length, Vector3 pos, Vector3 rot, float mass)
Add a capsule-shaped physics body to the world.
Creates a new dynamic capsule in the physics simulation. Capsules are useful for character controllers and objects that need smooth collision with the ground.
Parameters
ctx Pointer to the physics context
gfxCtx Pointer to the graphics context for texture assignment
radius Radius of the capsule caps
length Length of the cylindrical portion
pos Initial position of the capsule center
rot Initial rotation (Euler angles)
mass Mass of the capsule (0 for static object)
Returns
Pointer to the newly created entity
Note
Capsule combines a cylinder with two hemispherical ends
See also
entity
Examples
placer.c.
Definition at line 548 of file raylibODE.c.
References entity::body, CreateBaseEntity(), CreateGeomInfo(), GraphicsContext::cylinderTextures, rndf(), and PhysicsContext::space.
Referenced by CreateRandomEntity(), and main().
CreateCylinder()
entity * CreateCylinder (PhysicsContext * ctx, GraphicsContext * gfxCtx, float radius, float length, Vector3 pos, Vector3 rot, float mass)
Add a cylinder-shaped physics body to the world.
Creates a new dynamic cylinder in the physics simulation with the specified radius, length, position, rotation, and mass. ODE cylinders are aligned along the Z-axis by default.
Parameters
ctx Pointer to the physics context
gfxCtx Pointer to the graphics context for texture assignment
radius Radius of the cylinder
length Length of the cylinder (along Z-axis)
pos Initial position of the cylinder center
rot Initial rotation (Euler angles)
mass Mass of the cylinder (0 for static object)
Returns
Pointer to the newly created entity
Note
Cylinder is aligned along Z-axis as per ODE convention
Cylinder is assigned a random texture from the available cylinder textures
See also
entity
Examples
arm.c, and placer.c.
Definition at line 504 of file raylibODE.c.
References entity::body, CreateBaseEntity(), CreateGeomInfo(), GraphicsContext::cylinderTextures, rndf(), and PhysicsContext::space.
Referenced by CreateRandomEntity(), and main().
CreateCylinderGeom()
dGeomID CreateCylinderGeom (PhysicsContext * ctx, GraphicsContext * gfxCtx, float radius, float length, Vector3 pos)
Create a cylinder geom
This creates just the geometry, useful for building composite shapes
Parameters
ctx the physics context
gfxCtx the graphics context
radius radius of the cylinder
length length of the cylinder
pos where you want the geom positioned
Note
if you want to use this as a static collider in the world you will need to add it to the world and the physics context statics list
Examples
marbles.c.
Definition at line 356 of file raylibODE.c.
References CreateGeomInfo(), GraphicsContext::cylinderTextures, rndf(), and PhysicsContext::space.
Referenced by LoadLevel().
CreateDumbbell()
entity * CreateDumbbell (PhysicsContext * ctx, GraphicsContext * gfxCtx, float shaftRad, float shaftLen, float endRad, Vector3 pos, Vector3 rot, float mass)
Add a dumbbell-shaped composite physics body.
Creates a composite physics body consisting of a cylindrical shaft with two spherical ends. This demonstrates how to create custom composite shapes by combining multiple geometries.
Parameters
ctx Pointer to the physics context
gfxCtx Pointer to the graphics context for texture assignment
shaftRad Radius of the cylindrical shaft
shaftLen Length of the cylindrical shaft
endRad Radius of the end spheres
pos Initial position of the dumbbell center
rot Initial rotation (Euler angles)
mass Total mass of the dumbbell
Returns
Pointer to the newly created entity
Note
This is an example of creating composite shapes
Mass is distributed: 50% shaft, 25% each end
See also
entity
Examples
placer.c.
Definition at line 594 of file raylibODE.c.
References entity::body, CreateBaseEntity(), CreateGeomInfo(), GraphicsContext::cylinderTextures, rndf(), and PhysicsContext::space.
Referenced by CreateRandomEntity(), and main().
CreateGeomInfo()
geomInfo * CreateGeomInfo (bool collidable, Texture * texture, float uvScaleU, float uvScaleV)
Helper to allocate geomInfo with collision flag, optional texture, and UV scale this is useful when greating your own custom bodies for special purposes If this is attached to a geom on a body that is in the global entity list then this allocation will be automagically cleaned up.
Parameters
collidable should this geom cause collisions
texture which texture to use for the geom
uvScaleU texture scaling
uvScaleV texture scaling
Examples
arm.c, derby.c, fountain.c, piston.c, placer.c, ragdolls.c, raycasting.c, rotor.c, surfaces.c, and template.c.
Definition at line 751 of file raylibODE.c.
References geomInfo::collidable, gSurfaces, geomInfo::hew, geomInfo::surface, SURFACE_WOOD, geomInfo::texture, geomInfo::uvScaleU, and geomInfo::uvScaleV.
Referenced by CreateBox(), CreateBoxGeom(), CreateCapsule(), CreateCylinder(), CreateCylinderGeom(), CreateDumbbell(), CreateRagdoll(), CreateSphere(), CreateSphereGeom(), CreateStaticTrimesh(), CreateVehicle(), and main().
CreateMultiPiston()
MultiPiston * CreateMultiPiston (PhysicsContext * physCtx, GraphicsContext * graphics, Vector3 pos, Vector3 direction, int count, float sectionLen, float baseWidth, float strength)
add a multi section piston
Parameters
physCtx the physics context
graphics the graphical context
pos where the base of the piston should be positioned
direction a vector pointing from the base towards the end of the piston
count the number of sections for the piston
sectionLen How far each section extends fully retracted it will be a little longer than this as each section doesn't go into its parent 100%
baseWidth the width of the base
strength the maximum force the piston can use to extend or retract
Examples
marbles.c, and piston.c.
Definition at line 1285 of file raylibODE.c.
References entity::body, MultiPiston::count, CreateBox(), CreatePiston(), MultiPiston::joints, PISTON_GROUP, MultiPiston::sections, SetBodyOrientation(), SetPistonLimits(), and WORLD_GROUP.
Referenced by CreateLift(), and main().
CreatePiston()
dJointID CreatePiston (PhysicsContext * physCtx, entity * entA, entity * entB, float strength)
creates a piston using two entities as its base on extending sections
both entities should be positioned and oriented before calling this, they MUST NOT be in exactly the same position, as the vector between them is used as the axis for the piston
Parameters
physCtx the physics context
entA the base entity
entB the extending entity
strength the maximum force the piston can use
Examples
piston.c.
Definition at line 1203 of file raylibODE.c.
References entity::body, gSurfaces, SURFACE_METAL, and PhysicsContext::world.
Referenced by CreateMultiPiston(), and main().
CreateRandomEntity()
entity * CreateRandomEntity (PhysicsContext * ctx, GraphicsContext * gfxCtx, Vector3 pos, unsigned char mask)
Add a random physics object at the specified position.
Creates a random physics body (box, sphere, cylinder, capsule, or dumbbell) at the given position. Useful for testing and creating dynamic scenes without manually specifying each object.
Parameters
ctx Pointer to the physics context
gfxCtx Pointer to the graphics context
pos Position where the random object should be created
mask which shapes to choose from SHAPE_ALL for all of them SHAPE & ~SHAPE_CAPSULE for all but capsule etc
Returns
Pointer to the newly created entity
Note
Distribution: 20% boxes, 20% spheres, 20% cylinders, 20% capsules, 20% dumbbells
Mass is fixed at 10.0f for all random objects
Each type has randomized dimensions within reasonable ranges
Examples
arm.c, car.c, fountain.c, piston.c, placer.c, rotor.c, and terrain.c.
Definition at line 649 of file raylibODE.c.
References CreateBox(), CreateCapsule(), CreateCylinder(), CreateDumbbell(), CreateSphere(), rndf(), SHAPE_BOX, SHAPE_CAPSULE, SHAPE_CYLINDER, SHAPE_DUMBBELL, and SHAPE_SPHERE.
Referenced by main().
CreateRayCast()
RayCast * CreateRayCast (int maxHits, Vector3 pos, Vector3 direction, dReal length)
find the entities that collide with a ray
Parameters
maxHits Maximum number of hits that can be registered by the ray cast
pos Start position of the ray
direction vector pointing along the ray
length how long the ray should be
Note
A RayCast is not released by the framework and must be manually released there is no special function for this just free it.
Examples
raycasting.c.
Definition at line 839 of file raylibODE.c.
References RayCast::direction, RayCast::length, RayCast::maxHits, and RayCast::position.
Referenced by main().
CreateRotor()
dJointID CreateRotor (PhysicsContext * physCtx, entity * from, entity * to, Vector3 axis)
crates a rotor joint the joint is created with the anchor at the from enties location
Parameters
physCtx physics context holds all the physics globals
from the anchor entity for the joint
to if this is null the joint attaches to the world and is static
axis this determines the direction of rotation for the rotor you can think of it as the direction of the axle
Note
joints will get tidied up during world destruction, do destroy them if you no longer require them, in the arm example a joint is created and destroyed every time an object is caught and released
Examples
arm.c, and rotor.c.
Definition at line 1058 of file raylibODE.c.
References entity::body, and PhysicsContext::world.
Referenced by main().
CreateRotorPID()
RotorPID CreateRotorPID (float p, float i, float d, float lo, float hi)
create a rotor PID helper
Parameters
p proportional value for the PID
i integral value
d derivative
lo the low stop
hi the high stop
Note
a rotorPID contains a targetAngle, set this for your desired rotor angle
tuning a PID can be a bit of a dark art! I recommend looking at https://pidexplained.com/how-to-tune-a-pid-controller/ and the example pidJoint.c
Definition at line 1467 of file raylibODE.c.
References RotorPID::antiWindup, RotorPID::hi, RotorPID::Kd, RotorPID::Ki, RotorPID::Kp, and RotorPID::lo.
Referenced by main().
CreateSphere()
entity * CreateSphere (PhysicsContext * ctx, GraphicsContext * gfxCtx, float radius, Vector3 pos, Vector3 rot, float mass)
Add a sphere-shaped physics body to the world.
Creates a new dynamic sphere in the physics simulation with the specified radius, position, rotation, and mass. Spheres are efficient for collision detection and are commonly used for balls and round objects.
Parameters
ctx Pointer to the physics context
gfxCtx Pointer to the graphics context for texture assignment
radius Radius of the sphere
pos Initial position of the sphere center
rot Initial rotation (Euler angles)
mass Mass of the sphere (0 for static object)
Returns
Pointer to the newly created entity
Note
Sphere is assigned a random texture from the available sphere textures
See also
entity
PhysicsContext
Examples
arm.c, gravity.c, marbles.c, and placer.c.
Definition at line 460 of file raylibODE.c.
References entity::body, CreateBaseEntity(), CreateGeomInfo(), rndf(), PhysicsContext::space, and GraphicsContext::sphereTextures.
Referenced by CreateOrbiter(), CreateRandomEntity(), and main().
CreateSphereGeom()
dGeomID CreateSphereGeom (PhysicsContext * ctx, GraphicsContext * gfxCtx, float radius, Vector3 pos)
Create a sphere geom
This creates just the geometry, useful for building composite shapes
Parameters
ctx the physics context
gfxCtx the graphics context
radius radius of the sphere
pos where you want the geom positioned
Note
if you want to use this as a static collider in the world you will need to add it to the world and the physics context statics list
Examples
arm.c.
Definition at line 329 of file raylibODE.c.
References CreateGeomInfo(), rndf(), PhysicsContext::space, and GraphicsContext::sphereTextures.
Referenced by main().
CreateStaticTrimesh()
cnode_t * CreateStaticTrimesh (PhysicsContext * physCtx, GraphicsContext * gfxCtx, Model model, Texture * tex, float uvScale)
Create a static trimesh collision geometry from a model.
Creates a static trimesh (triangle mesh) collision geometry from a RayLib model. This allows arbitrary 3D models to be used as static collision objects in the physics simulation. The mesh is optimized for collision detection but does not move or respond to physics.
Parameters
physCtx Pointer to the physics context
gfxCtx Pointer to the graphics context
model RayLib model to create collision geometry from
tex Optional texture to apply to the mesh (can be NULL)
uvScale UV scaling factor for texture tiling
Returns
Pointer to the created node in the statics list
Note
The mesh is static and cannot be moved after creation
Supports custom textures and UV scaling for visual appearance
Stores model data for rendering with custom shaders
See also
GraphicsContext
Model
Examples
car.c, derby.c, and terrain.c.
Definition at line 714 of file raylibODE.c.
References clistAddNode(), CreateGeomInfo(), geomInfo::indices, GraphicsContext::shader, PhysicsContext::space, PhysicsContext::statics, geomInfo::triData, and geomInfo::visual.
Referenced by main().
DrawBodies()
void DrawBodies (struct GraphicsContext * ctx, PhysicsContext * pctx)
Draws all the dynamic bodies the framework is tracking.
Parameters
ctx the graphics context
pctx the physics context
Examples
arm.c, car.c, derby.c, fountain.c, gravity.c, marbles.c, piston.c, placer.c, ragdolls.c, raycasting.c, rotor.c, surfaces.c, template.c, and terrain.c.
Definition at line 1127 of file raylibODE.c.
References entity::body, __cnode::data, __clist::head, __cnode::next, and PhysicsContext::objList.
Referenced by main().
DrawGeom()
void DrawGeom (dGeomID geom, struct GraphicsContext * ctx)
Definition at line 960 of file raylibODE.c.
References GraphicsContext::ball, GraphicsContext::box, GraphicsContext::cylinder, geomInfo::hew, OdeToRayMat(), GraphicsContext::shader, geomInfo::texture, geomInfo::triggerOnCollide, geomInfo::uvScaleU, geomInfo::uvScaleV, and geomInfo::visual.
Referenced by DrawRagdoll(), and DrawStatics().
DrawStatics()
void DrawStatics (struct GraphicsContext * ctx, PhysicsContext * pctx)
draws the static geometries
As static geometries have no bodies they are handled a little different this will draw all the dGeomID's that are registed on the physics context static lists
Note
all geoms on the statics list must have attached geomInfo
Parameters
ctx the graphics context
pctx the physics context
Examples
arm.c, car.c, derby.c, fountain.c, gravity.c, marbles.c, piston.c, placer.c, ragdolls.c, raycasting.c, rotor.c, surfaces.c, template.c, and terrain.c.
Definition at line 1163 of file raylibODE.c.
References __cnode::data, DrawGeom(), __clist::head, __cnode::next, and PhysicsContext::statics.
Referenced by main().
FreeBodyAndGeoms()
void FreeBodyAndGeoms (dBodyID bdy)
given a body it will remove it and its geoms from ODE's world
Note
this is intended to be an internal function that might have use externally you would normally use FreeEntity
As well as freeing all associated metadata it will also remove the body and its geoms from the physics world
Parameters
bdy the dBodyID you want to free the attached meta data for
Definition at line 897 of file raylibODE.c.
Referenced by FreeEntity(), FreePhysics(), FreeRagdoll(), and FreeVehicle().
FreeEntity()
void FreeEntity (PhysicsContext * physCtx, entity * ent)
frees an entity
this is essentially destroying the entity it is no longer part of the world
Note
if iterrating through the global entity list while calling this, ensure you have stored the next node in the chain, for use at the end of the while loop as obviously node->next won't work
Parameters
physCtx physics context
ent the entity to destroy
Examples
arm.c, car.c, fountain.c, gravity.c, marbles.c, piston.c, placer.c, raycasting.c, rotor.c, surfaces.c, and terrain.c.
Definition at line 1184 of file raylibODE.c.
References entity::body, clistDeleteNode(), FreeBodyAndGeoms(), entity::node, and PhysicsContext::objList.
Referenced by main(), and updateGravity().
FreeMultiPiston()
void FreeMultiPiston (MultiPiston * mp)
frees all the internal resources of a multipiston
Parameters
mp the multipiston to free
Note
this is not done automagically (like dynamic bodies for example) when you create a multipiston add a call to this function in your exit path
Examples
marbles.c, and piston.c.
Definition at line 1264 of file raylibODE.c.
References MultiPiston::joints, and MultiPiston::sections.
Referenced by main().
OdeToRayMat()
void OdeToRayMat (const dReal * R, Matrix * m)
sets a raylib matrix from an ODE rotation matrix
Parameters
R a pointer to the ODE matrix
m a pointer to a Raylib Matrix
Examples
derby.c.
Definition at line 951 of file raylibODE.c.
Referenced by DrawGeom(), and main().
PickEntity()
entity * PickEntity (PhysicsContext * physCtx, GraphicsContext * gfxCtx, Vector3 * hitPoint)
this will return the first entity that the camera is directly pointed at while useful in the examples and likely for other things, it also serves as an example of how you can do this yourself for other things
Parameters
physCtx the physics context (global physics info)
gfxCtx the graphics context (global info usful for graphics)
hitPoint pass a pointer to a Vector3 this will be set with the location of the intersecton
Returns
a pointer to the entity that was found.
Examples
placer.c.
Definition at line 794 of file raylibODE.c.
References GraphicsContext::camera, RayHit::depth, RayHit::geom, RayHit::pos, and PhysicsContext::space.
Referenced by main().
PinEntities()
dJointID PinEntities (PhysicsContext * physCtx, entity * entA, entity * entB)
pin two entities together
Parameters
physCtx the physics context
entA the first entity
entB the second entity
The constraint will attempt to keep the relative position and orientation of the two entities as it was when this is called.
Definition at line 1406 of file raylibODE.c.
References entity::body, and PhysicsContext::world.
Referenced by main().
PinEntityToWorld()
dJointID PinEntityToWorld (PhysicsContext * physCtx, entity * ent)
pins an entity to the world
This joint will attempt to keep the position and orientation of the body static, position and rotate the body as needed before calling this
Parameters
physCtx physics context
ent The entity to pin to the world
Returns
the joint id of the constraint
Examples
marbles.c, and piston.c.
Definition at line 1388 of file raylibODE.c.
References entity::body, and PhysicsContext::world.
Referenced by CreateLift(), and main().
RayToOdeMat()
void RayToOdeMat (Matrix * m, dReal * R)
set an ODE matrix to the same as a Raylib Matrix
Parameters
m a pointer to the Raylib matrix
R a pointer to an ODE matrix
Definition at line 939 of file raylibODE.c.
rndf()
float rndf (float min, float max)
Generate a random float in the specified range.
Parameters
min Minimum value (inclusive)
max Maximum value (inclusive)
Returns
Random float between min and max
Note
Uses rand() from stdlib - consider seeding with srand() for better randomness
Examples
arm.c, car.c, fountain.c, gravity.c, piston.c, placer.c, ragdolls.c, rotor.c, surfaces.c, and terrain.c.
Definition at line 238 of file raylibODE.c.
Referenced by CreateBox(), CreateBoxGeom(), CreateCapsule(), CreateCylinder(), CreateCylinderGeom(), CreateDumbbell(), CreateOrbiter(), CreateRandomEntity(), CreateSphere(), CreateSphereGeom(), GetRagdollSpawnPosition(), GetSpawnOnSphereBorder(), and main().
SetBodyOrientation()
void SetBodyOrientation (dBodyID body, Vector3 direction)
sets to bodies orientation to align with a vector
Parameters
body the ODE body id you want to orient
direction the vector you want the body oriented along
Examples
piston.c.
Definition at line 1348 of file raylibODE.c.
Referenced by CreateMultiPiston(), and main().
SetBodyOrientationEuler()
void SetBodyOrientationEuler (dBodyID bdy, float p, float y, float r)
sets a bodies orientation
Parameters
bdy the body id
p the pitch
y the yaw
r the roll
Note
you shouldn't be doing this every frame rather use forces (torque)
Definition at line 1424 of file raylibODE.c.
SetEntityHew()
void SetEntityHew (entity * ent, Color c)
changes the hew (tint) of all anentities geoms
go through each geom attached to the entities body and change their hew or tint
Parameters
ent pointer to the entity
c new colour to use
Examples
arm.c, fountain.c, and surfaces.c.
Definition at line 1091 of file raylibODE.c.
References entity::body, and geomInfo::hew.
Referenced by main().
SetEntitySurfaces()
void SetEntitySurfaces (entity * ent, SurfaceMaterial * mat)
changes the surface material of all an entities geoms
go through each geom attached to the entities body and change their surface properties
Parameters
ent pointer to the entity
mat new surface material to use
Examples
raycasting.c, and surfaces.c.
Definition at line 1111 of file raylibODE.c.
References entity::body, and geomInfo::surface.
Referenced by main().
SetGeomOrientationEuler()
void SetGeomOrientationEuler (dGeomID g, float p, float y, float r)
sets a geoms orientation
Parameters
g the geom id
p the pitch
y the yaw
r the roll
This is most useful when you are creating bodies with composite geoms or for use with a static geom
Examples
raycasting.c.
Definition at line 1442 of file raylibODE.c.
Referenced by main().
SetMultiPistonVelocity()
void SetMultiPistonVelocity (MultiPiston * mp, float velocity)
set a MultiPiston's velocity
While setting all the join velocities in the piston it also ensures all the bodies are active
Parameters
mp the multipiston you want to change the speed of
velocity the speed you want the piston set to
Examples
marbles.c, and piston.c.
Definition at line 1333 of file raylibODE.c.
References entity::body, MultiPiston::count, MultiPiston::joints, and MultiPiston::sections.
Referenced by main().
SetPistonLimits()
void SetPistonLimits (dJointID joint, float min, float max)
sets the limits of travel for a piston
min must be smaller than max values can be negative
Parameters
joint the ODE joint id of the joint you want to change
min the low end stop point
max the high end stop point
Examples
piston.c.
Definition at line 1249 of file raylibODE.c.
Referenced by CreateMultiPiston(), and main().
StepPhysics()
int StepPhysics (PhysicsContext * physCtx)
Step the physics simulation forward.
This function advances the physics simulation by stepping the world forward using fixed time steps. It handles the frame time accumulation and performs multiple physics steps if necessary to maintain simulation stability and accuracy.
Parameters
physCtx Pointer to the physics context containing the world and state
Returns
Number of physics steps performed this frame
Note
Uses dWorldQuickStep for faster but less accurate simulation
Maximum number of steps is limited by maxPsteps to prevent spiral of death
See also
PhysicsContext
dWorldQuickStep
Examples
arm.c, car.c, derby.c, fountain.c, gravity.c, marbles.c, piston.c, placer.c, ragdolls.c, raycasting.c, rotor.c, surfaces.c, template.c, and terrain.c.
Definition at line 260 of file raylibODE.c.
References PhysicsContext::contactgroup, PhysicsContext::frameTime, maxPsteps, nearCallback(), physSlice, PhysicsContext::space, and PhysicsContext::world.
Referenced by main(), and updateGravity().
UpdateRotorPID()
void UpdateRotorPID (RotorPID * pid, dJointID joint)
update rotor PID
Parameters
pid the RotorPID to update
joint the rotor joint to align with the targetAngle of the RotorPID
Definition at line 1487 of file raylibODE.c.
References RotorPID::hi, RotorPID::integral, RotorPID::Kd, RotorPID::Ki, RotorPID::Kp, RotorPID::lastError, RotorPID::lo, and RotorPID::targetAngle.
Referenced by main().
Variable Documentation
physSlice
const float physSlice = 1.0 / 240.0
Physics simulation time slice.
The fixed time step used for physics simulation. ODE recommends using fixed time steps for consistent results. 1/240 = ~240 Hz update rate. the framework will step as many times as it needs to to keep up with realtime in this sized steps
Definition at line 227 of file raylibODE.c.
Referenced by StepPhysics().