rlights.c File Reference
#include <stdbool.h>
#include "raylib.h"
#include "rlights.h"
Functions
Light CreateLight (int type, Vector3 position, Vector3 target, Color color, Shader shader)
void UpdateLightValues (Shader shader, Light light)
Function Documentation
CreateLight()
Light CreateLight (int type, Vector3 position, Vector3 target, Color color, Shader shader)
Definition at line 26 of file rlights.c.
References Light::color, Light::colorLoc, Light::enabled, Light::enabledLoc, MAX_LIGHTS, Light::position, Light::positionLoc, Light::target, Light::targetLoc, Light::type, Light::typeLoc, and UpdateLightValues().
Referenced by CreateGraphics().
UpdateLightValues()
void UpdateLightValues (Shader shader, Light light)
Definition at line 55 of file rlights.c.
References Light::color, Light::colorLoc, Light::enabled, Light::enabledLoc, Light::position, Light::positionLoc, Light::target, Light::targetLoc, Light::type, and Light::typeLoc.
Referenced by CreateLight().