rlights.h File Reference
Data Structures
struct Light
Macros
#define MAX_LIGHTS 4
Enumerations
enum LightType { LIGHT_DIRECTIONAL = 0
, LIGHT_POINT
 }
Functions
Light CreateLight (int type, Vector3 position, Vector3 target, Color color, Shader shader)
void UpdateLightValues (Shader shader, Light light)
Macro Definition Documentation
MAX_LIGHTS
#define MAX_LIGHTS 4
Definition at line 39 of file rlights.h.
Referenced by CreateLight().
Enumeration Type Documentation
LightType
enum LightType
Enumerator
LIGHT_DIRECTIONAL
LIGHT_POINT
Definition at line 64 of file rlights.h.
Function Documentation
CreateLight()
Light CreateLight (int type, Vector3 position, Vector3 target, Color color, Shader shader)
Definition at line 26 of file rlights.c.
References Light::color, Light::colorLoc, Light::enabled, Light::enabledLoc, MAX_LIGHTS, Light::position, Light::positionLoc, Light::target, Light::targetLoc, Light::type, Light::typeLoc, and UpdateLightValues().
Referenced by InitGraphics().
UpdateLightValues()
void UpdateLightValues (Shader shader, Light light)
Definition at line 55 of file rlights.c.
References Light::color, Light::colorLoc, Light::enabled, Light::enabledLoc, Light::position, Light::positionLoc, Light::target, Light::targetLoc, Light::type, and Light::typeLoc.
Referenced by CreateLight().