/home/chris/development/RayLibOdeMech/examples/rotor.c File Reference
#include "init.h"
#include "exampleCamera.h"
Macros
#define screenWidth 1920/1.2
#define screenHeight 1080/1.2
#define WALL_GROUP 0x00000004
#define ROTOR_GROUP 0x00000008
Functions
int main (void)
Macro Definition Documentation
ROTOR_GROUP
#define ROTOR_GROUP 0x00000008
Examples
rotor.c.
Definition at line 33 of file rotor.c.
Referenced by main().
screenHeight
#define screenHeight 1080/1.2
Definition at line 28 of file rotor.c.
screenWidth
#define screenWidth 1920/1.2
Definition at line 27 of file rotor.c.
WALL_GROUP
#define WALL_GROUP 0x00000004
Examples
rotor.c.
Definition at line 32 of file rotor.c.
Referenced by main().
Function Documentation
main()
int main (void)
Definition at line 35 of file rotor.c.
References entity::body, GraphicsContext::camera, clistAddNode(), CreateBox(), CreateGeomInfo(), CreateGraphics(), CreatePhysics(), CreateRandomEntity(), CreateRotor(), __cnode::data, DrawBodies(), DrawStatics(), FreeEntity(), FreeGraphics(), FreePhysics(), GraphicsContext::groundTexture, gSurfaces, __clist::head, maxPsteps, __cnode::next, NUM_OBJ, PhysicsContext::objList, PLANE_SIZE, PLANE_THICKNESS, rndf(), ROTOR_GROUP, screenHeight, screenWidth, SetupCamera(), SHAPE_ALL, SHAPE_DUMBBELL, PhysicsContext::space, PhysicsContext::statics, StepPhysics(), geomInfo::surface, SURFACE_EARTH, SURFACE_ICE, SURFACE_RUBBER, UpdateExampleCamera(), WALL_GROUP, and WORLD_GROUP.