/home/chris/development/RayLibOdeMech/examples/surfaces.c File Reference
#include "init.h"
#include "exampleCamera.h"
Macros
#define screenWidth 1920/1.2
#define screenHeight 1080/1.2
Functions
int main (void)
Macro Definition Documentation
screenHeight
#define screenHeight 1080/1.2
Definition at line 28 of file surfaces.c.
screenWidth
#define screenWidth 1920/1.2
Definition at line 27 of file surfaces.c.
Function Documentation
main()
int main (void)
Definition at line 32 of file surfaces.c.
References entity::body, GraphicsContext::camera, clistAddNode(), CreateBox(), CreateGeomInfo(), CreateGraphics(), CreatePhysics(), __cnode::data, DrawBodies(), DrawStatics(), FreeEntity(), FreeGraphics(), FreePhysics(), GraphicsContext::groundTexture, gSurfaces, __clist::head, maxPsteps, __cnode::next, PhysicsContext::objList, PLANE_SIZE, PLANE_THICKNESS, rndf(), screenHeight, screenWidth, SetEntityHew(), SetEntitySurfaces(), SetupCamera(), PhysicsContext::space, PhysicsContext::statics, StepPhysics(), geomInfo::surface, SURFACE_COUNT, SURFACE_EARTH, and UpdateExampleCamera().