/home/chris/development/RayLibOdeMech/examples/template.c File Reference
#include "raylibODE.h"
Macros
#define screenWidth 1920/1.2
#define screenHeight 1080/1.2
Functions
int main (void)
Macro Definition Documentation
screenHeight
#define screenHeight 1080/1.2
Definition at line 27 of file template.c.
screenWidth
#define screenWidth 1920/1.2
Definition at line 26 of file template.c.
Function Documentation
main()
int main (void)
Definition at line 31 of file template.c.
References GraphicsContext::camera, clistAddNode(), CreateGeomInfo(), CreateGraphics(), CreatePhysics(), DrawBodies(), DrawStatics(), FreeGraphics(), FreePhysics(), GraphicsContext::groundTexture, PLANE_SIZE, PLANE_THICKNESS, screenHeight, screenWidth, SetupCamera(), PhysicsContext::space, PhysicsContext::statics, StepPhysics(), and UpdateCameraControl().