/home/chris/development/RayLibOdeMech/examples/terrain.c File Reference
#include "raylibODE.h"
Macros
#define screenWidth 1920/1.2
#define screenHeight 1080/1.2
Functions
int main (void)
Macro Definition Documentation
screenHeight
#define screenHeight 1080/1.2
Definition at line 27 of file terrain.c.
screenWidth
#define screenWidth 1920/1.2
Definition at line 26 of file terrain.c.
Function Documentation
main()
int main (void)
Definition at line 32 of file terrain.c.
References entity::body, GraphicsContext::camera, CreateGraphics(), CreatePhysics(), CreateRandomEntity(), CreateStaticTrimesh(), __cnode::data, DrawBodies(), DrawStatics(), FreeEntity(), FreeGraphics(), FreePhysics(), GraphicsContext::groundTexture, __clist::head, maxPsteps, __cnode::next, NUM_OBJ, PhysicsContext::objList, rndf(), screenHeight, screenWidth, SetupCamera(), SHAPE_ALL, StepPhysics(), and UpdateCameraControl().