vehicle.c File Reference
Vehicle simulation implementation.
#include "vehicle.h"
#include <stdlib.h>
#include <math.h>
Functions
vehicle * CreateVehicle (PhysicsContext *pctx, struct GraphicsContext *ctx, Vector3 pos, Vector3 carScale, float wheelRadius, float wheelWidth)
Create a physics-based vehicle.
void UpdateVehicle (vehicle *car, float accel, float steer)
Update vehicle control inputs.
void FreeVehicle (PhysicsContext *pctx, vehicle *car)
this releases all resources in use by a vehicle struct
void UnflipVehicle (vehicle *car)
flips an upside down vehicle
Detailed Description
Vehicle simulation implementation.
This file provides a complete vehicle simulation using ODE's Hinge2 joints to simulate wheels with suspension. The vehicle consists of a chassis body connected to wheel bodies via simulated suspension joints.
Author
Chris Camacho (codifies - http://bedroomcoders.co.uk/)
Date
2021-2026
Vehicle Structure
The vehicle is composed of:
1 chassis body (box shape)
4 wheel bodies (cylinder shape)
1 anti-sway mass (lowered center of gravity)
4 Hinge2 joints (suspension + steering)
1 Fixed joint (anti-sway attachment)
Control
Use UpdateVehicle() to control:
accel: Forward/backward acceleration
steer: Steering angle
Definition in file vehicle.c.
Function Documentation
CreateVehicle()
vehicle * CreateVehicle (PhysicsContext * pctx, struct GraphicsContext * ctx, Vector3 pos, Vector3 carScale, float wheelRadius, float wheelWidth)
Create a physics-based vehicle.
Creates a complete vehicle simulation with chassis, wheels, and suspension. The vehicle uses Hinge2 joints for realistic wheel suspension and steering mechanics.
Parameters
pctx Pointer to physics context
ctx Pointer to graphics context
pos Initial position of the vehicle
carScale Dimensions of the chassis (x=length, y=height, z=width)
wheelRadius Radius of the wheels
wheelWidth Width of the wheels
Returns
Pointer to newly created vehicle structure
Note
Front wheels are driving wheels
Front wheels also provide steering
Anti-sway mass lowers center of gravity to prevent tipping
See also
UpdateVehicle
FreeVehicle
Examples
car.c, and derby.c.
Definition at line 56 of file vehicle.c.
References vehicle::bodies, entity::body, vehicle::bodyCount, GraphicsContext::boxTextures, clistAddNode(), CreateGeomInfo(), GraphicsContext::cylinderTextures, vehicle::geoms, gSurfaces, vehicle::joints, entity::node, PhysicsContext::objList, PhysicsContext::space, geomInfo::surface, SURFACE_RUBBER, and PhysicsContext::world.
FreeVehicle()
void FreeVehicle (PhysicsContext * pctx, vehicle * car)
this releases all resources in use by a vehicle struct
Parameters
pctx the physics context
car the vehicle to free
Examples
car.c, and derby.c.
Definition at line 233 of file vehicle.c.
References vehicle::bodies, vehicle::bodyCount, clistDeleteNode(), FreeBodyAndGeoms(), entity::node, and PhysicsContext::objList.
UnflipVehicle()
void UnflipVehicle (vehicle * car)
flips an upside down vehicle
Parameters
car the vehicle to flip
Note
this is a quick hack, it violently pops the vehicle back upright - there are better ways of doing this!
Examples
derby.c.
Definition at line 258 of file vehicle.c.
References vehicle::bodies.
UpdateVehicle()
void UpdateVehicle (vehicle * car, float accel, float steer)
Update vehicle control inputs.
Applies acceleration and steering to the vehicle. This should be called every frame with current control inputs.
Parameters
car Pointer to the vehicle structure
accel Acceleration input (-1.0 to 1.0, negative for reverse)
steer Steering input (-1.0 to 1.0, negative for left)
Note
Set accel to 0 for coasting (wheels spin free)
Front wheels provide steering and all-wheel drive
Examples
car.c, and derby.c.
Definition at line 190 of file vehicle.c.
References vehicle::joints.