vehicle.h File Reference
#include "raylibODE.h"
Data Structures
struct vehicle
Macros
#define VEH_PART_COUNT 7
#define WHEEL_COUNT 5
Typedefs
typedef struct vehicle vehicle
Functions
vehicle * CreateVehicle (PhysicsContext *pctx, struct GraphicsContext *ctx, Vector3 pos, Vector3 carScale, float wheelRadius, float wheelWidth)
Create a physics-based vehicle.
void UpdateVehicle (vehicle *car, float accel, float steer)
Update vehicle control inputs.
void FreeVehicle (PhysicsContext *pctx, vehicle *car)
this releases all resources in use by a vehicle struct
void unflipVehicle (vehicle *car)
flips an upside down vehicle
Macro Definition Documentation
VEH_PART_COUNT
#define VEH_PART_COUNT 7
Definition at line 6 of file vehicle.h.
WHEEL_COUNT
#define WHEEL_COUNT 5
Definition at line 7 of file vehicle.h.
Typedef Documentation
vehicle
typedef struct vehicle vehicle
Function Documentation
CreateVehicle()
vehicle * CreateVehicle (PhysicsContext * pctx, struct GraphicsContext * ctx, Vector3 pos, Vector3 carScale, float wheelRadius, float wheelWidth)
Create a physics-based vehicle.
Creates a complete vehicle simulation with chassis, wheels, and suspension. The vehicle uses Hinge2 joints for realistic wheel suspension and steering mechanics.
Parameters
pctx Pointer to physics context
ctx Pointer to graphics context
pos Initial position of the vehicle
carScale Dimensions of the chassis (x=length, y=height, z=width)
wheelRadius Radius of the wheels
wheelWidth Width of the wheels
Returns
Pointer to newly created vehicle structure
Note
Front wheels are driving wheels
Front wheels also provide steering
Anti-sway mass lowers center of gravity to prevent tipping
See also
UpdateVehicle
FreeVehicle
Definition at line 56 of file vehicle.c.
References vehicle::bodies, entity::body, vehicle::bodyCount, GraphicsContext::boxTextures, clistAddNode(), CreateGeomInfo(), GraphicsContext::cylinderTextures, vehicle::geoms, vehicle::joints, entity::node, PhysicsContext::objList, PhysicsContext::space, and PhysicsContext::world.
FreeVehicle()
void FreeVehicle (PhysicsContext * pctx, vehicle * car)
this releases all resources in use by a vehicle struct
Parameters
pctx the physics context
car the vehicle to free
Definition at line 231 of file vehicle.c.
References vehicle::bodies, vehicle::bodyCount, clistDeleteNode(), FreeBodyAndGeoms(), entity::node, and PhysicsContext::objList.
unflipVehicle()
void unflipVehicle (vehicle * car)
flips an upside down vehicle
Parameters
car the vehicle to flip
Note
this is a quick hack, it violently pops the vehicle back upright - there are better ways of doing this!
Definition at line 256 of file vehicle.c.
References vehicle::bodies.
UpdateVehicle()
void UpdateVehicle (vehicle * car, float accel, float steer)
Update vehicle control inputs.
Applies acceleration and steering to the vehicle. This should be called every frame with current control inputs.
Parameters
car Pointer to the vehicle structure
accel Acceleration input (-1.0 to 1.0, negative for reverse)
steer Steering input (-1.0 to 1.0, negative for left)
Note
Set accel to 0 for coasting (wheels spin free)
Front wheels provide steering and all-wheel drive
Definition at line 188 of file vehicle.c.
References vehicle::joints.